import {CheckCircle2, Filter, SlidersHorizontal, X} from 'lucide-react'
import {Catalog, isRelational, labelFor, planDimensions, planMetrics, QueryPlan, QueryResponse} from '../lib/api'
import QueryLineage from './QueryLineage'

export default function AnswerContext({result, catalog, canDrill, busy, onRun}: {result: QueryResponse; catalog: Catalog | null; canDrill: boolean; busy: boolean; onRun: (plan: QueryPlan) => void}) {
  const plan = result.plan, metrics = planMetrics(plan), dimensions = planDimensions(plan)
  const filters = !plan ? [] : isRelational(plan) ? plan.filters.map((filter, index) => ({key: `${filter.field}-${index}`, label: `${labelFor(filter.field)} ${filter.op} ${Array.isArray(filter.value) ? filter.value.join(', ') : filter.value}`, remove: () => onRun({...plan, filters: plan.filters.filter((_, i) => i !== index)})})) : Object.entries(plan.filters).map(([key, value]) => ({key, label: value, remove: () => {const next = {...plan, filters: {...plan.filters}}; delete next.filters[key]; onRun(next)}}))
  return <aside className="context-panel"><div className="context-heading"><span className="mint-icon"><SlidersHorizontal size={17}/></span><h3>Behind this answer</h3></div><div className="context-item"><span>{metrics.length > 1 ? 'MEASURES' : 'MEASURE'}</span><div>{metrics.map(id => {const metric = catalog?.metrics.find(item => item.id === id); return <div className="answer-measure" key={id}><strong>{metric?.label || labelFor(id)}</strong><p>{metric?.description}</p></div>})}</div></div><div className="context-item"><span>BREAKDOWN</span><strong>{dimensions.length ? dimensions.map(id => catalog?.dimensions.find(item => item.id === id)?.label || labelFor(id)).join(' + ') : 'One total'}</strong><p>{canDrill ? 'Select a chart value to filter and explore another breakdown.' : 'Matching records, aggregated using the approved definition.'}</p></div><div className="context-item"><span>ACTIVE FILTERS</span><div className="filter-tags">{filters.length ? filters.map(filter => <span key={filter.key}><Filter size={11}/>{filter.label}<button aria-label={`Remove ${filter.key.replace(/-\d+$/, '')} filter`} disabled={busy} onClick={filter.remove}><X size={11}/></button></span>) : <span>No dimension filters</span>}</div>{isRelational(plan) && <div className="relational-context-notes">{plan.population === 'all' && <p>Current + archived records · {plan.set_operation === 'union' ? 'duplicates removed' : 'all records retained'}</p>}{plan.having.map((item, index) => <p key={index}>{labelFor(item.metric)} {item.op} {item.value} after aggregation</p>)}{plan.exists && <p>{plan.exists.negate ? 'Without' : 'With'} matching {labelFor(plan.exists.relation)}{plan.exists.filters.length ? ` · ${plan.exists.filters.map(item => `${labelFor(item.field)} ${item.op} ${item.value}`).join(', ')}` : ''}</p>}{plan.comparison && <p>{labelFor(plan.comparison.metric)} above the group average</p>}</div>}</div>{result.lineage && <QueryLineage result={result} compact/>}<div className="context-note"><CheckCircle2 size={16}/><p>Model interprets intent.<br/><strong>The validated plan controls execution.</strong></p></div></aside>
}
