'use client'

import {useState} from 'react'
import {Catalog, formatValue, isRelational, labelFor, QueryResponse} from '../lib/api'

const colors = ['#555D38', '#B69D78', '#788377', '#A16D51', '#8B9569', '#74675C', '#B5BA94', '#66523F', '#9B9B85', '#80684A', '#B58B77', '#585E52']
export function relationalChartTypes(result: QueryResponse, catalog?: Catalog | null): string[] {
  if (!isRelational(result.plan) || !result.data.length) return []
  const {metrics, dimensions} = result.plan, rows = result.data
  if (!dimensions.length) return ['stat']
  const types = ['bar'], metric = metrics[0]
  if ((metrics.length === 1 || !!result.calculations?.length) && dimensions.length === 1 && (dimensions[0] === 'month' || rows.every(row => /^\d{4}-\d{2}(?:-\d{2})?$/.test(String(row[dimensions[0]]))))) types.push('line', 'area')
  if (catalog?.metrics.find(item => item.id === metric)?.additive === true && metrics.length === 1 && dimensions.length === 1 && rows.length <= 12 && rows.every(row => typeof row[metric] === 'number' && Number(row[metric]) >= 0) && rows.reduce((sum, row) => sum + Number(row[metric]), 0) > 0) types.push('donut')
  if (metrics.length === 2 && dimensions.length <= 2 && rows.filter(row => metrics.every(id => typeof row[id] === 'number' && Number.isFinite(row[id]))).length >= 2) types.push('scatter')
  return types
}

export default function RelationalChart({result, catalog, type, compact = false, onSelect}: {result: QueryResponse; catalog?: Catalog | null; type?: string; compact?: boolean; onSelect?: (dimension: string, value: string) => void}) {
  const [active, setActive] = useState<number | null>(null)
  if (!isRelational(result.plan)) return null
  const {metrics, dimensions} = result.plan, rows = result.data, first = metrics[0]
  const names = (id: string) => catalog?.metrics.find(item => item.id === id)?.label || catalog?.dimensions.find(item => item.id === id)?.label || labelFor(id)
  const fmt = (value: number, metric = first, short = false) => formatValue(value, metric, short, catalog)
  const title = (row: typeof rows[number]) => dimensions.map(id => row[id] == null ? 'Missing group' : String(row[id])).join(' · ')
  const select = (index: number) => {setActive(index); const value = rows[index][dimensions[0]]; if (onSelect && value != null) onSelect(dimensions[0], String(value))}
  const types = relationalChartTypes(result, catalog), chartType = types.includes(type || '') ? type! : types[0]
  if (!rows.length) return <div className="empty-chart">No matching data. Try a wider date range or remove a filter.</div>
  if (!dimensions.length) return <div className={`multi-stat ${compact ? 'compact' : ''}`} data-testid="query-chart">{metrics.map(metric => <div className="single-stat" key={metric}><span>{names(metric)}</span><strong data-testid="metric-value">{rows[0][metric] == null ? '—' : fmt(Number(rows[0][metric]), metric)}</strong><p>{rows[0][metric] == null ? 'No matching values.' : 'Calculated from the approved definition.'}</p></div>)}</div>
  const rowLabel = (index: number, metric = first) => `${title(rows[index])}: ${rows[index][metric] == null ? 'No matching values' : fmt(Number(rows[index][metric]), metric)}`
  const hint = onSelect ? 'Select a group to filter its first breakdown. The saved plan runs without a model call.' : `${rows.length} groups · values from the database`
  if (chartType === 'donut') {
    const total = rows.reduce((sum, row) => sum + Number(row[first]), 0), radius = 78, circumference = 2 * Math.PI * radius
    let offset = 0
    return <div className={`relational-donut ${compact ? 'compact' : ''}`} data-testid="query-chart" data-chart-type="donut"><div className="donut-layout"><svg viewBox="0 0 260 240" role="img" aria-label={`${names(first)} distribution`}><circle cx="130" cy="115" r={radius} fill="none" stroke="#E8E3D4" strokeWidth="27"/>{rows.map((row, index) => {const length = Number(row[first]) / total * circumference, start = offset; offset += length; return <circle key={index} data-testid="donut-segment" role="button" tabIndex={0} aria-label={rowLabel(index)} cx="130" cy="115" r={radius} fill="none" stroke={colors[index % colors.length]} strokeWidth={active === index ? 32 : 27} strokeDasharray={`${length} ${circumference - length}`} strokeDashoffset={-start} transform="rotate(-90 130 115)" onMouseEnter={() => setActive(index)} onFocus={() => setActive(index)} onClick={() => select(index)} onKeyDown={event => {if (event.key === 'Enter' || event.key === ' ') {event.preventDefault(); select(index)}}}><title>{rowLabel(index)} ({(Number(row[first]) / total * 100).toFixed(1)}%)</title></circle>})}<text x="130" y="110" textAnchor="middle" className="donut-total">{fmt(total, first, true)}</text><text x="130" y="132" textAnchor="middle" className="donut-total-label">{names(first)}</text></svg><div className="chart-legend">{rows.map((row, index) => <button key={index} onClick={() => select(index)} aria-label={rowLabel(index)}><i style={{background: colors[index % colors.length]}}/><span>{title(row)}</span><strong>{fmt(Number(row[first]))}</strong></button>)}</div></div><p className="chart-hint">Share of the displayed groups. {hint}</p></div>
  }
  if (chartType === 'scatter') {
    const [xMetric, yMetric] = metrics, paired = rows.map((row, index) => ({row, index})).filter(({row}) => metrics.every(id => typeof row[id] === 'number' && Number.isFinite(row[id])))
    const xs = paired.map(({row}) => Number(row[xMetric])), ys = paired.map(({row}) => Number(row[yMetric]))
    const minX = Math.min(...xs, 0), maxX = Math.max(...xs, 0), minY = Math.min(...ys, 0), maxY = Math.max(...ys, 0)
    const spanX = maxX - minX || 1, spanY = maxY - minY || 1, width = 760, height = 300, left = 80, right = 30, top = 24, bottom = 55
    return <div className={`relational-scatter line-chart ${compact ? 'compact' : ''}`} data-testid="query-chart" data-chart-type="scatter"><div className="chart-readout" aria-live="polite">{active === null ? 'Hover or select a point to inspect both measures.' : `${title(rows[active])} · ${names(xMetric)} ${fmt(Number(rows[active][xMetric]), xMetric)} · ${names(yMetric)} ${fmt(Number(rows[active][yMetric]), yMetric)}`}</div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${names(yMetric)} versus ${names(xMetric)}`}>{[0, .25, .5, .75, 1].map(ratio => {const x = left + ratio * (width - left - right), y = top + (1 - ratio) * (height - top - bottom); return <g key={ratio}><line x1={left} x2={width - right} y1={y} y2={y} stroke="#DEDCCD" strokeDasharray="4 5"/><text x={left - 12} y={y + 4} textAnchor="end">{fmt(minY + spanY * ratio, yMetric, true)}</text><text x={x} y={height - bottom + 20} textAnchor="middle">{fmt(minX + spanX * ratio, xMetric, true)}</text></g>})}{paired.map(({row, index}) => <circle key={index} data-testid="scatter-point" role="button" tabIndex={0} aria-label={`${title(row)}: ${names(xMetric)} ${fmt(Number(row[xMetric]), xMetric)}, ${names(yMetric)} ${fmt(Number(row[yMetric]), yMetric)}`} cx={left + (Number(row[xMetric]) - minX) / spanX * (width - left - right)} cy={top + (1 - (Number(row[yMetric]) - minY) / spanY) * (height - top - bottom)} r={active === index ? 8 : 6} fill={colors[index % colors.length]} stroke="#FAF7EF" strokeWidth="2" onMouseEnter={() => setActive(index)} onFocus={() => setActive(index)} onClick={() => select(index)} onKeyDown={event => {if (event.key === 'Enter' || event.key === ' ') {event.preventDefault(); select(index)}}}><title>{title(row)}</title></circle>)}<text x={(left + width - right) / 2} y={height - 6} textAnchor="middle">{names(xMetric)}</text><text transform={`translate(15 ${(top + height - bottom) / 2}) rotate(-90)`} textAnchor="middle">{names(yMetric)}</text></svg><p className="chart-hint">{paired.length < rows.length ? `${rows.length - paired.length} groups with missing measures omitted. ` : ''}{hint}</p></div>
  }
  if (chartType === 'line' || chartType === 'area') {
    const ordered = rows.map((row, index) => ({row, index})).sort((a, b) => String(a.row[dimensions[0]]).localeCompare(String(b.row[dimensions[0]])))
    const values = rows.filter(row => row[first] != null).map(row => Number(row[first])), min = Math.min(...values, 0), max = Math.max(...values, 0), span = max - min || 1
    const width = 760, height = 245, left = 68, right = 24, top = 20, bottom = 36, base = top + (1 - (0 - min) / span) * (height - top - bottom)
    const coords = ordered.map(({row, index}, position) => ({index, value: row[first], x: left + position * (width - left - right) / Math.max(rows.length - 1, 1), y: row[first] == null ? null : top + (1 - (Number(row[first]) - min) / span) * (height - top - bottom)}))
    const segments: typeof coords[] = []; let current: typeof coords = []
    for (const point of coords) {if (point.y === null) {if (current.length) segments.push(current); current = []} else current.push(point)}
    if (current.length) segments.push(current)
    return <div className={`line-chart relational-line ${compact ? 'compact' : ''}`} data-testid="query-chart" data-chart-type={chartType}><div className="chart-readout" aria-live="polite">{active == null ? 'Values are ordered by date. Missing values remain gaps.' : rowLabel(active)}</div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${names(first)} over time`}>{[0, .25, .5, .75, 1].map(ratio => {const y = top + (1 - ratio) * (height - top - bottom); return <g key={ratio}><line x1={left} x2={width - right} y1={y} y2={y} stroke="#DEDCCD" strokeDasharray="4 5"/><text x={left - 12} y={y + 4} textAnchor="end">{fmt(min + span * ratio, first, true)}</text></g>})}{segments.map((points, index) => <g key={index}>{chartType === 'area' && <path d={`M ${points[0].x},${base} L ${points.map(point => `${point.x},${point.y}`).join(' L ')} L ${points[points.length - 1].x},${base} Z`} fill="#555D38" fillOpacity="0.12"/>}<polyline points={points.map(point => `${point.x},${point.y}`).join(' ')} fill="none" stroke="#555D38" strokeWidth="3" strokeLinejoin="round"/></g>)}{coords.map((point, position) => <g key={point.index}>{point.y !== null && <circle role="button" tabIndex={0} data-testid="chart-point" aria-label={rowLabel(point.index)} cx={point.x} cy={point.y} r={active === point.index ? 7 : 5} fill="#FAF7EF" stroke="#555D38" strokeWidth="2" onMouseEnter={() => setActive(point.index)} onFocus={() => setActive(point.index)} onClick={() => select(point.index)} onKeyDown={event => {if (event.key === 'Enter' || event.key === ' ') {event.preventDefault(); select(point.index)}}}><title>{rowLabel(point.index)}</title></circle>}{(rows.length <= 12 || position % Math.ceil(rows.length / 12) === 0) && <text x={point.x} y={height - 10} textAnchor="middle">{String(rows[point.index][dimensions[0]])}</text>}</g>)}</svg><p className="chart-hint">{hint}</p></div>
  }
  return <div className={`relational-bars ${compact ? 'compact' : ''}`} data-testid="query-chart" data-chart-type="bar">{metrics.map((metric, metricIndex) => {
    const values = rows.filter(row => row[metric] != null).map(row => Number(row[metric])), min = Math.min(...values, 0), max = Math.max(...values, 0), span = max - min || 1
    return <section className="bar-chart" key={metric}>{metrics.length > 1 && <h3>{names(metric)}</h3>}<div className="chart-scale"><span>{fmt(min, metric, true)}</span><span>{fmt(min + span / 2, metric, true)}</span><span>{fmt(min + span, metric, true)}</span></div>{rows.map((row, index) => <button key={index} className="bar-row" data-testid="chart-bar" aria-label={`${names(metric)} · ${rowLabel(index, metric)}`} onClick={() => select(index)} onMouseEnter={() => setActive(index)} onFocus={() => setActive(index)}><span className="bar-label" title={title(row)}>{title(row)}</span><span className="bar-track">{row[metric] != null && <span className="bar-fill" style={{position: 'absolute', background: colors[metrics.length > 1 ? metricIndex : dimensions.length > 1 ? Array.from(new Set(rows.map(item => item[dimensions[1]]))).indexOf(row[dimensions[1]]) % colors.length : index % 4], left: `${(Math.min(Number(row[metric]), 0) - min) / span * 100}%`, width: `${Math.abs(Number(row[metric])) / span * 100}%`}}/>}</span><strong>{row[metric] == null ? '—' : fmt(Number(row[metric]), metric, compact)}</strong></button>)}</section>
  })}<p className="chart-hint">{metrics.length > 1 ? 'Each measure has its own labeled scale. ' : ''}{dimensions.length > 1 ? `Groups show ${dimensions.map(names).join(' and ')}. ` : ''}{hint}</p></div>
}
