'use client'

import {ArrowRight, LoaderCircle, Plus, X} from 'lucide-react'
import {Catalog, CatalogField, newRelationalPlan, RelationalFilter, RelationalQueryPlan, withRelationalDimensions} from '../lib/api'

const comparisons: [RelationalFilter['op'], string][] = [['eq', 'is'], ['ne', 'is not'], ['gt', 'greater than'], ['gte', 'at least'], ['lt', 'less than'], ['lte', 'at most'], ['in', 'is one of']]
function FilterRows({fields, filters, onChange, prefix = 'Filter'}: {fields: CatalogField[]; filters: RelationalFilter[]; onChange: (value: RelationalFilter[]) => void; prefix?: string}) {
  const update = (index: number, patch: Partial<RelationalFilter>) => onChange(filters.map((filter, i) => i === index ? {...filter, ...patch} : filter))
  return <div className="relational-filters">{filters.map((filter, index) => {
    const field = fields.find(item => item.id === filter.field), list = filter.op === 'in'
    const value = Array.isArray(filter.value) ? filter.value.join(', ') : String(filter.value)
    return <div className="relational-filter-row" key={index}>
      <label>Field<select aria-label={`${prefix} ${index + 1} field`} value={filter.field} onChange={event => update(index, {field: event.target.value, op: 'eq', value: fields.find(item => item.id === event.target.value)?.type === 'number' ? 0 : ''})}>{fields.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
      <label>Condition<select aria-label={`${prefix} ${index + 1} operator`} value={filter.op} onChange={event => {const op = event.target.value as RelationalFilter['op']; update(index, {op, value: op === 'in' ? (Array.isArray(filter.value) ? filter.value : [filter.value]) : (Array.isArray(filter.value) ? filter.value[0] ?? '' : filter.value)})}}>{comparisons.filter(([op]) => field?.type === 'number' ? true : ['eq', 'ne', 'in'].includes(op)).map(([op, text]) => <option key={op} value={op}>{text}</option>)}</select></label>
      <label>{list ? 'Values, separated by commas' : 'Value'}{field?.values?.length && !list ? <select aria-label={`${prefix} ${index + 1} value`} value={value} onChange={event => update(index, {value: event.target.value})}><option value="">Choose a value</option>{field.values.map(item => <option key={item} value={item}>{item}</option>)}</select> : <input aria-label={`${prefix} ${index + 1} value`} type={field?.type === 'number' && !list ? 'number' : 'text'} step="any" value={value} required onChange={event => update(index, {value: list ? event.target.value.split(',').map(part => field?.type === 'number' && part.trim() ? Number(part.trim()) : part.trim()) : field?.type === 'number' && event.target.value !== '' ? Number(event.target.value) : event.target.value})}/>}</label>
      <button className="icon-button" type="button" aria-label={`Remove ${prefix.toLowerCase()} ${index + 1}`} onClick={() => onChange(filters.filter((_, i) => i !== index))}><X size={15}/></button>
    </div>
  })}<button className="text-button" type="button" disabled={!fields.length || filters.length >= 8} onClick={() => onChange([...filters, {field: fields[0].id, op: 'eq', value: fields[0].type === 'number' ? 0 : fields[0].values?.[0] || ''}])}><Plus size={13}/>Add {prefix.toLowerCase()}</button></div>
}

export default function RelationalBuilder({catalog, plan, onChange, onRun, busy}: {catalog: Catalog; plan: RelationalQueryPlan; onChange: (plan: RelationalQueryPlan) => void; onRun: () => void; busy: boolean}) {
  const fields = Array.from(new Map([...catalog.dimensions, ...catalog.fields || []].filter(item => item.id !== 'month').map(item => [item.id, item])).values())
  const relations = catalog.exists_relations || [], relation = relations.find(item => item.id === plan.exists?.relation)
  const set = (patch: Partial<RelationalQueryPlan>) => onChange({...plan, ...patch})
  const toggleMetric = (id: string) => {
    const metrics = plan.metrics.includes(id) ? plan.metrics.filter(item => item !== id) : [...plan.metrics, id]
    if (!metrics.length || metrics.length > 3) return
    set({metrics, having: plan.having.filter(item => metrics.includes(item.metric)), comparison: plan.comparison && metrics.includes(plan.comparison.metric) ? plan.comparison : null, sort: metrics.includes(plan.sort.field) || plan.dimensions.includes(plan.sort.field) ? plan.sort : {field: metrics[0], direction: 'desc'}})
  }
  return <form className="builder relational-builder" data-testid="relational-builder" onSubmit={event => {event.preventDefault(); onRun()}}>
    <fieldset><legend>Measures <small>Choose up to three</small></legend><div className="relational-choices">{catalog.metrics.map(item => <label key={item.id} title={item.description}><input type="checkbox" aria-label={`Measure ${item.label}`} checked={plan.metrics.includes(item.id)} disabled={!plan.metrics.includes(item.id) && plan.metrics.length >= 3} onChange={() => toggleMetric(item.id)}/><span>{item.label}</span></label>)}</div></fieldset>
    <div className="builder-grid"><label>Group by<select aria-label="Group by" value={plan.dimensions[0] || ''} onChange={event => {const dimensions = event.target.value ? [event.target.value, ...plan.dimensions.slice(1).filter(item => item !== event.target.value)] : []; onChange(withRelationalDimensions(plan, dimensions))}}><option value="">Totals only</option>{catalog.dimensions.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
      <label>Then group by<select aria-label="Then group by" disabled={!plan.dimensions.length} value={plan.dimensions[1] || ''} onChange={event => onChange(withRelationalDimensions(plan, event.target.value ? [plan.dimensions[0], event.target.value] : plan.dimensions.slice(0, 1)))}><option value="">No second group</option>{catalog.dimensions.filter(item => item.id !== plan.dimensions[0]).map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
      <label>Records<select aria-label="Record population" value={plan.population} onChange={event => set({population: event.target.value as RelationalQueryPlan['population'], set_operation: event.target.value === 'primary' ? 'union_all' : plan.set_operation})}>{(catalog.populations || [{id: 'primary', label: 'Current records'}, {id: 'all', label: 'Current and archived records'}]).map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
      {plan.population === 'all' && <label>Combine sources<select aria-label="Combine sources" value={plan.set_operation} onChange={event => set({set_operation: event.target.value as RelationalQueryPlan['set_operation']})}><option value="union_all">Keep all records (UNION ALL)</option><option value="union">Remove duplicate records (UNION)</option></select></label>}
      <label>From<input aria-label="From" type="date" value={plan.date_from || ''} onChange={event => set({date_from: event.target.value || null})}/></label><label>To<input aria-label="To" type="date" value={plan.date_to || ''} onChange={event => set({date_to: event.target.value || null})}/></label>
    </div>
    <details className="builder-detail" open={plan.filters.length > 0 || undefined}><summary>Filter individual records <small>WHERE</small></summary><FilterRows fields={fields} filters={plan.filters} onChange={filters => set({filters})}/></details>
    <details className="builder-detail" open={plan.having.length > 0 || !!plan.comparison || undefined}><summary>Filter aggregate results <small>HAVING & comparison</small></summary>{plan.having.map((having, index) => <div className="relational-filter-row" key={index}><label>Measure<select aria-label={`Aggregate filter ${index + 1} measure`} value={having.metric} onChange={event => set({having: plan.having.map((item, i) => i === index ? {...item, metric: event.target.value} : item)})}>{catalog.metrics.filter(item => plan.metrics.includes(item.id)).map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Condition<select aria-label={`Aggregate filter ${index + 1} operator`} value={having.op} onChange={event => set({having: plan.having.map((item, i) => i === index ? {...item, op: event.target.value as typeof having.op} : item)})}>{comparisons.filter(([op]) => op !== 'in').map(([op, text]) => <option key={op} value={op}>{text}</option>)}</select></label><label>Value<input aria-label={`Aggregate filter ${index + 1} value`} type="number" step="any" required value={Number.isFinite(having.value) ? having.value : ''} onChange={event => set({having: plan.having.map((item, i) => i === index ? {...item, value: event.target.valueAsNumber} : item)})}/></label><button className="icon-button" type="button" aria-label={`Remove aggregate filter ${index + 1}`} onClick={() => set({having: plan.having.filter((_, i) => i !== index)})}><X size={15}/></button></div>)}<button className="text-button" type="button" disabled={plan.having.length >= 3} onClick={() => set({having: [...plan.having, {metric: plan.metrics[0], op: 'gt', value: 0}], comparison: null})}><Plus size={13}/>Add aggregate filter</button><label className="comparison-label">Compare each group with the average<select aria-label="Above average comparison" disabled={!plan.dimensions.length} value={plan.comparison?.metric || ''} onChange={event => set({comparison: event.target.value ? {kind: 'above_average', metric: event.target.value} : null, having: event.target.value ? [] : plan.having})}><option value="">No comparison</option>{catalog.metrics.filter(item => plan.metrics.includes(item.id)).map(item => <option key={item.id} value={item.id}>{item.label} above the group average</option>)}</select></label></details>
    {relations.length > 0 && <details className="builder-detail" open={!!plan.exists || undefined}><summary>Match related records <small>EXISTS / NOT EXISTS</small></summary><div className="builder-grid"><label>Related records<select aria-label="Related records" value={plan.exists?.relation || ''} onChange={event => set({exists: event.target.value ? {relation: event.target.value, negate: false, filters: []} : null})}><option value="">Do not filter by related records</option>{relations.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>{plan.exists && <label>Match<select aria-label="Related record match" value={plan.exists.negate ? 'without' : 'with'} onChange={event => set({exists: {...plan.exists!, negate: event.target.value === 'without'}})}><option value="with">Has a matching record</option><option value="without">Has no matching record</option></select></label>}</div>{plan.exists && relation && <FilterRows prefix="Related filter" fields={relation.fields} filters={plan.exists.filters} onChange={filters => set({exists: {...plan.exists!, filters}})}/>}</details>}
    <div className="builder-grid"><label>Sort field<select aria-label="Sort field" value={plan.sort.field} onChange={event => set({sort: {...plan.sort, field: event.target.value}})}>{[...catalog.metrics, ...catalog.dimensions].filter(item => [...plan.metrics, ...plan.dimensions].includes(item.id)).map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Sort direction<select aria-label="Sort direction" value={plan.sort.direction} onChange={event => set({sort: {...plan.sort, direction: event.target.value as 'asc' | 'desc'}})}><option value="desc">Descending</option><option value="asc">Ascending</option></select></label><label>Result limit<select aria-label="Result limit" value={plan.limit} onChange={event => set({limit: Number(event.target.value)})}>{Array.from(new Set([plan.limit, 5, 10, 25, 50, 100])).sort((a, b) => a - b).map(limit => <option key={limit} value={limit}>{limit} results</option>)}</select></label></div>
    <div className="builder-actions"><button className="text-button" type="button" onClick={() => onChange(newRelationalPlan(catalog))}>Reset filters</button><button className="button primary" type="submit" disabled={busy}>{busy ? <LoaderCircle size={15} className="spin"/> : <ArrowRight size={15}/>}Run analysis</button></div>
  </form>
}
